# experiment params
exp_dir: exp_mdx/               # Path to the directory where the training logs and checkpoints will be stored

model_name: WaveletHTDemucs          # This choice affects choice of models and loss functions in code

exp_name: all_targets_bleeding       # This will create a directory under the 'exp_dir/model_name',
                            # change this for different experiments

cpu_run: false              # Whether to turn off GPU use

disable_pbar: false


# optimization params
epochs: 681                 # number of epochs
lr: 0.0003                   # initial learning rate

scheduler: null
optimizer: AdamW
optimizer_args:
  betas: [0.9, 0.999]
  weight_decay: 0.005
  amsgrad: true
  fused: true
grad_clip_norm: 5.0


min_lr: 7e-5                # minimum learning rate
use_previous_lr: false
batch_size: 32              # batch size
num_batches_per_epoch: 300
amp: false                   # whether to use automatic mixed precision training


# checkpoint and validation params
checkpoint_path: ''         # provide checkpoint path if you want to restart training or finetune
resume_from_last: false     # if true, finds the last checkpoint in the current experiment directory and resumes
save_interval: 1          # Number of  epochs before saving a checkpoint
eval_interval: 1          # Number of epochs before running validation
audio_log_interval: 1      # Number of epochs before logging audio
num_workers: 32             # Number of workers for training data loading



loss_fn: l1_with_mean_teacher          # which loss function to use, check losses/loss_switcher.py
loss_weights: [[1, 1, 0], [1, 2, 1], [0, 2, 1]]
loss_weights_milestones: [100, 200]
mean_teacher_interval: 2

skip_eval: true            # whether to skip validation
eval_metric: global_sdr
val_patch_length: 7       # if null, use full length validation, else use this length for validation
val_hop_length: 1.75
use_window: false
save_eval_wavs: true


# ema params:
ema:
  batch: [0.9995]
  epoch: []
# the following parameters are passed directly as key-value arguments to the respective class init functions
# so please be careful, the names are actual function argument names.

# model parameters, check specific model class for more details
model_args:
  audio_channels: 2
  target_sources: ['vocals', 'drums', 'bass', 'other']
  mixing_sources: ['vocals', 'drums', 'bass', 'other']
  levels: 3
  wave:  bior6.8
  nfft: 4096
  hop: 1024
  freq_emb_weight: 0.2
  hidden_sizes_wavelet: [384, 192, 96, 48]
  wavelet_enc_channels:
    - [[48, 4], [96, 4], [192, 4], [384, 4]]
    - [[24, 4], [48, 4], [96, 4], [192, 4]]
    - [[8, 4], [12, 4], [24, 4], [48, 4], [96, 2]]
    - [[8, 4], [12, 4], [24, 4], [48, 4], [48, 4]]
  time_enc_channels: [[12, 4], [ 24, 4 ], [ 48, 4 ], [ 96, 4 ], [ 192, 4 ], [ 384, 2 ] ]
  hidden_size_t: 384
  freq_enc_channels: [ [ 24, 4 ], [ 48, 4 ], [ 96, 4 ], [ 192, 4 ], [ 384, 4 ] ]
  hidden_size_f: 384
  norm_starts: 4
  rescale: 0.1
  lstm_starts: null
  attn_starts: null
  encoder_params:
    kernel_size: 8
    residual_params:
      depth: 2
      compress: 4
      kernel_size: 3
      init: 0.001
    context: 0
    norm_groups: 4
  decoder_params:
    kernel_size: 8
    residual_params:
      depth: 2
      compress: 4
      kernel_size: 3
      init: 0.001
    context: 1
    norm_groups: 4
  cross_transformer_params:
    # general
    layer_scale: True
    gelu: True
    hidden_scale: 4
    num_heads: 8
    num_layers: 5
    dropout: 0.02
    # cross first False
    cross_first: False

    # positional embedding
    emb: sin
    max_positions: 10000
    max_period: 10000.0
    sin_random_shift: 0
    weight_pos_embed: 1.0
    cape_mean_normalize: True
    cape_augment: True
    cape_glob_loc_scale: [ 5000.0, 1.0, 1.4 ]

    # norm before encoder
    norm_in: True
    norm_in_group: False

    # norm inside encoder
    group_norm: False
    norm_first: True
    norm_out: True

    # optim
    weight_decay: 0
    lr: null
  augmentations:
    Remix:
      proba: 1
      group_size: 4
    RandomGain:
      p: 1
      high: 1.25
      low: 0.25
    SwapChannel: {}
    RandomSignFlip: {}


# data loader arguments
data_loader_args:

  train_loader: random_mix_training_dataloader

  # for training data loader
  train:
    data_roots:
      - DATASETS/SDX2023/moisesdb23_bleeding_v1.0
    metadata_file_prefix: train
    noisy: []
    mixing_sources: ['vocals', 'drums', 'bass', 'other']
    sample_rate: 44100
    mono: false
    segment_length: 7
    normalize: true
    center: false
    shuffle: true
    random_segments: true
    num_workers: 32
    cycle: true
    drop_last: true
    return_song_name: false
    filter_silence: true
    cpu_aug: false
